routes/web.php
<?php

use App\Http\Controllers\QueueOrderController;
use App\Http\Controllers\QueueController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ListController;
use App\Http\Controllers\ArchiveController;
use function GuzzleHttp\Promise\queue;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\DeliveringControler;
use App\Http\Controllers\Driver\DriverHomeController;
use App\Http\Controllers\Auth\NewPasswordController;
use App\Http\Controllers\Auth\PasswordResetController;
use Illuminate\Support\Facades\Notification;
use App\Notifications\EmailNotification;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'role:operator'], function () {
    //route for List with 2 extra function push & delete 
    Route::get('/push/{id}', [ListController::class, 'push'])->name('push');
    Route::delete('/deleteItem/{id}', [ListController::class, 'deleteItem'])->name('deleteItem');
    Route::resource('list', 'ListController')->names([
        'index' => 'list'
    ]);
    //route for Queue
    Route::post('/addgroup', [QueueController::class, 'addgroup']);
    Route::post('/assigngroup', [QueueController::class, 'assignGroup']);    
    Route::post('/pushtodelivery', [QueueController::class, 'pushDeliver']);    
    Route::resource('queue', 'QueueController')->names([
        'index' => 'queue'
    ]);    
    //route for archives
    Route::get('/archive', [ArchiveController::class, 'index'])->name('archive');
    Route::get('/archive/{id}', [ArchiveController::class, 'timeframe']);
    Route::get('search', 'ArchiveController@search');
    //route for delivering orders
    Route::get('/delivering', [DeliveringControler::class, 'index'])->name('delivering');
    Route::post('/editdeliveringstatus', [DeliveringControler::class, 'updateUnfulfilled']);
    Route::post('/pusharchive/{groupid}', [DeliveringControler::class, 'pusharchive']);

    Route::get('/register', [RegisterController::class, 'index'])->name('register');
});


Route::group(['middleware' => 'role:driver'], function () {
    Route::get('/driverhome', [DriverHomeController::class, 'index'])->name('driver.home');
    //Route for Login and Register
    Route::get('/driver/{id}', [DriverHomeController::class, 'driver'])->name('driver');
    //Route for Driver
    //swap orders in delivering group
    Route::post('/swaporder', [DriverHomeController::class, 'swaporder']);
    //report an order
    Route::post('/reportorder', [DriverHomeController::class, 'reportorder']);
    Route::post('/markmessageread', [DriverHomeController::class, 'markmessageread']);
    //complete an order
    Route::post('/completeorder', [DriverHomeController::class, 'completeorder']);
    //pickup order
    Route::get('/pickup/{id}', [DriverHomeController::class, 'pickup'])->name('pickup');
    //send auto message upon completion
    Route::post('/sendautomessage', [DriverHomeController::class, 'completeorder']);
});


Route::get('/', function () {
    return view('auth.login');
});


Route::post('/register', [RegisterController::class, 'store']);
Route::post('/login', [LoginController::class, 'store']);
Route::post('/logout', [LogoutController::class, 'remove'])->middleware('auth')->name('logout');


Route::group(['middleware' => 'guest'], function () {
    // Passsword Recovery
    Route::get('/forgot-password', [PasswordResetController::class, 'create'])->name('password.request');
    Route::post('/forgot-password', [PasswordResetController::class, 'store'])->name('password.email');
    Route::get('/reset-password/{token}', [NewPasswordController::class, 'create'])->name('password.reset');
    Route::post('/reset-password', [NewPasswordController::class, 'store'])->name('password.update');

    Route::get('/login', [LoginController::class, 'index'])->name('login');
});

app/Http/Controllers/ListController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use App\Models\Order;
use App\Models\Customer;
use App\Models\Item;
use DB;
use App\Rules\ArrayAtLeastOneRequired;

class ListController extends Controller
{
    // only authorize user can view this page
    public function __construct(){

        $this->middleware(['auth']);
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //List page will display all the orders with a status list/1
        //checking to see if a pagination option was selected
        //if not, display 5 orders by default
        $items = $request->items ?? 10; 
        
        $data = Order::where('status','=', 1)
                ->with('customer')
                ->with('item')
                ->paginate($items);
        
        $querystringarray=(['items'=>$request->items,'page'=>$request->page]);
        $data->appends($querystringarray);
        return view('list.list', ['data'=>$data, 'items'=>$items] );
    
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         //create button will direct user to create page
        return view('list.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $order=Order::all();

        //validating the information entered
        $request->validate([
            'firstname'=> 'required|max:255',
            'lastname'=> 'required|max:255',
            'email'=> 'required|email|max:255',
            'address'=> 'required|max:255',
            'city'=> 'required|max:255',
            'zipcode'=> 'required|max:255',
            'state'=>'required',
            'phonenumber'=> 'required|max:255',
            'deliverydate'=>'required',
            'myItems' =>[new ArrayAtLeastOneRequired()],
            'myQuantity' =>[new ArrayAtLeastOneRequired()],

        ]);
        
        //creating a row in the customer table
        Customer::create([
            'firstname'=> $request->firstname,
            'lastname'=> $request->lastname,
            'email'=> $request->email,
            'address'=> $request->address,
            'city'=> $request->city,
            'zipcode'=> $request->zipcode,
            'state'=> $request->state,
            'phonenumber'=> $request->phonenumber,
        ]);
        
        //getting the new customer to be used in the new order
        $last=Customer::all()->last();
        
        //creating a new order row
        Order::create([
            'status'=> 1,
            'customerid'=> $last->id,
            'deliveryinstruction'=>$request->deliveryinstruction,
            'deliverydate'=>$request->deliverydate,
            
        ]);
        
        //getting the new order to add items to
        $lastOrder=Order::all()->last();
        
        //adding all the items added on the form to order
        for ($i=0;$i<count($request->myItems);$i++){
            //making sure all the items info was entered correctly
            if ($request->myItems[$i]!=null && $request->myQuantity[$i]!=null){
                Item::create([
                    'orderid' =>$lastOrder->id,
                    'itemname'=>$request->myItems[$i],
                    'itemquantity' =>$request->myQuantity[$i],
                ]);
            }
        }

        //returning the user to list, and flash a success notification
        return redirect('list')->with('message','<div class ="alert alert-success alert-dhp">Order Successfully Created.</div>');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //getting the order that user wants to edit
        $data = Order::where('id',$id)->with('item')->with('customer')->get();
        return view('list.edit',[ 'data'=>$data,'id'=>$id]);
 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //deleting an item 
        $action = $request->input('action');
        if ($action=='delete'){
            $order = Order::where('id',$id)->with('item')->first();
            $items= $order->item->first();
            $items->delete();
            return back();
        }

        //validating the information entered
        $request->validate([
            'firstname'=> 'required|max:255',
            'lastname'=> 'required|max:255',
            'email'=> 'required|email|max:255',
            'address'=> 'required|max:255',
            'city'=> 'required|max:255',
            'zipcode'=> 'required|max:255',
            'state'=> 'required|max:255',
            'phonenumber'=> 'required|max:255',
            'deliverydate'=>'required',
            'myItems'=> 'required|min:1',
            'myQuantity'=>'required|min:1',
        ]);
        
        //getting all the information entered through request
        $input=$request->all();

        //getting the order using id
        $order = Order::find($id);
        
        //getting all the items in that order
        $items = $order->item;

        //changing the order information
        $order->customer->update(['firstname'=>$request->firstname]);
        $order->customer->update(['lastname'=>$request->lastname]);
        $order->customer->update(['email'=>$request->email]);
        $order->customer->update(['phonenumber'=>$request->phonenumber]);
        $order->customer->update(['address'=>$request->address]);
        $order->customer->update(['city'=>$request->city]);
        $order->customer->update(['zipcode'=>$request->zipcode]);
        $order->update(['deliveryinstruction'=>$request->deliveryinstruction]);
        $order->update(['deliverydate'=>$request->deliverydate]);
 
        $count=0;
        //checking to see how many new items added 
        foreach ($items as $item){
            if ($request->myItems[$count]!=null && $request->myQuantity[$count]!=null){
                $item->update(['itemname'=>$request->myItems[$count]]);
                $item->update(['itemquantity'=>$request->myQuantity[$count]]);
                $count++;
            }else if($request->myItems[$count]==null && $request->myQuantity[$count]==null){
                $item->delete();
            }
        }
 
        //adding all items to the order
        for ($i=$count;$i<count($request->myItems);$i++){

            //checking to see if both the item name and item quantity was entered
            if ($request->myItems[$i]!=null && $request->myQuantity[$i]!=null){
                Item::create([
                    'orderid'=>$id,
                    'itemname'=>$request->myItems[$i],
                    'itemquantity'=>$request->myQuantity[$i],
                ]);
            }
        }
        //flash a success notification that an order has been created
        return redirect()->route('list')->with('message','<div class ="alert alert-success alert-dhp">Order Successfully Editted.</div>');;
   
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {//deleting an order
        //getting the order using id
        $order=Order::findorfail($id);
        //getting the customer id
        $custid=$order->customerid;
        //getting the customer
        $customer=Customer::findorfail($custid);
         
        //delete order
        $order->delete();
        //delete customer
        $customer->delete();
        return redirect()->route('list')->with('message','<div class ="alert alert-success alert-dhp">Delete an order successfully</div>');
    
    }
    
    public function deleteItem($id)
    {//deleting an item
        //getting the item id
        $items= Item::find($id);
        $items->delete();
        return back();
    }

    public function push(Request $request, $id){
        //pushing an order from list to queue, 
        //changing the status from 1 to 2
        $order = Order::find($id);
        $order->update(['status'=>2]);

        //display a success notification that the order was pushed 
        return redirect('list')->with('message','<div class ="alert alert-success alert-dhp">Push to Queue Successfully</div>');
    }
}

resources/views/List/create.blade.php
@extends ('layouts.app')

@section('content')
<link rel="stylesheet" href="{{asset('css/create.css')}} ">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <div class="container content">
    
    <form action="/list" method="POST" name="myForm" id="myForm" onsubmit="return validateForm()" style="border:none" >
    
    @csrf

    <h2 class="content-heading">Custom Order</h2>
      <div>
        <form action="/action_page.php" >
        <div class="form-container">
          
        <label for="fname" class="order-label">First Name</label>
        <input class="form"type="text" id="firstname" name="firstname" value= "{{old('firstname')}}" placeholder="First name"> <br>
        @error('firstname')
        <div class='error'>
        {{ $message }}
        </div>
        @enderror
      </div>

      <div class="form-container">
        <label for="lname">Last Name</label>
        <input class="form"type="text" id="lastname" name="lastname" value= "{{old('lastname')}}" placeholder="Last name" value="{{old('name')}}">
        @error('lastname')
        <div class="error">
        {{ $message }}
        </div>
        @enderror
      </div>

      <div class="form-container">
        <label for="email">Email</label>
        <input class="form"type="text" id="email" name="email" value= "{{old('email')}}" placeholder="i.e. hello@deltahandpies.com">
        @error('email')
        <div class='error'>
        {{ $message }}
        </div>
        @enderror
      </div>

      <div class="form-container">
        <label for="phonenumber">Phone Number</label>
        <input class="form"type="text" id="phonenumber" name="phonenumber" value= "{{old('phonenumber')}}" placeholder="Your phonenumber..">
        @error('phonenumber')
        <div class='error'>
        {{ $message }}
        </div>
        @enderror
      </div>

      <div class="form-container">
        <label for="adrs">Address</label>
        <input class="form"type="text" id="address" name="address" value= "{{old('address')}}" placeholder="Your address..">
        @error('address')
        <div class='error'>
        {{ $message }}
        </div>
        @enderror
      </div>

      <div class="form-container">
        <label for="city">City</label>
        <input class="form"type="text" id="city" name="city" value= "{{old('city')}}" placeholder="i.e. Sacramento">
        @error('city')
        <div class='error'>
        {{ $message }}
        </div>
        @enderror
      </div>

      <div class="form-container">
        <label for="zip">Zipcode</label>
        <input class="form"type="text" id="zip" name="zipcode" value= "{{old('zipcode')}}" placeholder="i.e. 95825">
        @error('zipcode')
        <div class='error'>
        {{ $message }}
        </div>
        @enderror
      </div>




      <div class="form-container">
        <label for="state">State</label>
        <input class="form"type="text" id="state" name="state" value= "{{old('state')}}" placeholder="i.e. CA">
        @error('state')
        <div class='error'>
        {{ $message }}
        </div>
        @enderror
      </div>

      <div class="form-container">
        <label for="state">Delivery Instruction</label>
        <input class="textarea" type="text" id="deliveryinstruction" value= "{{old('deliveryinstruction')}}" name="deliveryinstruction" placeholder="instruction...">
      </div>


      <div class="form-container">
        <label for="zip">Delivery Date</label>
        <input class="form" type="date" id="deliverydate" name="deliverydate" value= "{{old('deliverydate')}}">
        @error('deliverydate')
        <div class='error'>
        {{ $message }}
        </div>
        @enderror
      </div>



      <div class="container1 add-item">

        <label for="itemname" >Item Name</label>
        <label for="itemname"style="padding-left:35%;">Item Quantity</label><br>
        <input type="text" name="myItems[]"  placeholder="Item name" value= "{{old('myItems.0')}}">
        @error('myItems')
        <div class='error'>
        <p>Items is Required</p>
        </div>
        @enderror
        <input type="text" name="myQuantity[]"  placeholder="Item quantity" value= "{{old('myQuantity.0')}}">
        @error('myQuantity')
        <div class='error' style="padding-left:50%;">
        <p>Item Quantity is Required</p>
        </div>
        @enderror

        <button class="add_form_field btn btn-primary"><i class="fa fa-plus"></i></button>
      </div>
      <div class="form-container">
        <button type="submit" class="btn btn-primary">Submit</button>  
      </div>
      
    </div>
  </form>
</div>

  

  <script>
    $(document).ready(function() {
      var max_fields = 40;
      var wrapper = $(".container1");
      var add_button = $(".add_form_field");

      var x = 1;
      $(add_button).click(function(e) {
        e.preventDefault();
        if (x < max_fields) {
          x++;
          $(wrapper).append('<div class="row "><input type="text" name="myItems[]"placeholder="Item name"> <input type="text" name="myQuantity[]"placeholder="Item quantity"> <a href="javascript:void(0);" class="delete btn btn-danger"><i class="fa fa-minus"></i></a></div>'); //add input box
          } else {
            alert('You Reached the limits')
        }
      });

      $(wrapper).on("click", ".delete", function(e) {
        e.preventDefault();
        $(this).closest('div.row').remove();
        x--;
      })
    });
  </script>


@endsection

resources/views/List/edit.blade.php
@extends ('layouts.app')

@section('content')
  <link rel="stylesheet" href="{{asset('css/create.css')}} ">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  @if(Session::has('success'))
            <div class="alert alert-success alert-dhp">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>Success!</strong> {{ Session::get('message', '') }}
            </div>
@endif
  <div class="container content">
    
    <form action="{{url('list/'.$id)}}" method="POST" name="myForm" id="myForm" onsubmit="return validateForm()" style="border:none" >
    @csrf

    <h2 class="content-heading">Edit Order</h2>
      <div>
        <!--<form action="/action_page.php" >-->
        <div class="form-container">
          

          
          @foreach ($data as $data)
       
          <label for="fname" class="order-label">First Name</label>
          <input class="form"type="text" id="firstname" name="firstname" placeholder="First name" value="{{old('firstname') ?? $data->customer->firstname}}"> <br>
          @error('firstname')
            <div class='error'>
              {{ $message }}
            </div>
          @enderror
        </div>
      

      <div class="form-container">
        <label for="lname">Last Name</label>
        <input class="form"type="text" id="lastname" name="lastname" value="{{old('lastname') ?? $data->customer->lastname}}">
        @error('lastname')
        <div class="error">
        {{ $message }}
        </div>
        @enderror
      </div>

      <div class="form-container">
        <label for="email">Email</label>
        <input class="form"type="text" id="email" name="email" value="{{old('email') ?? $data->customer->email}}">
        @error('email')
        <div class='error'>
        {{ $message }}
        </div>
        @enderror
      </div>

      <div class="form-container">
        <label for="phonenumber">phone</label>
        <input class="form"type="text" id="phonenumber" name="phonenumber" value="{{old('phonenumber') ?? $data->customer->phonenumber}}">
        @error('phonenumber')
        <div class='error'>
        {{ $message }}
        </div>
        @enderror
      </div>

      <div class="form-container">
        <label for="adrs">Address</label>
        <input class="form"type="text" id="address" name="address" value="{{old('address') ?? $data->customer->address}}">
        @error('address')
        <div class='error'>
        {{ $message }}
        </div>
        @enderror
      </div>

      <div class="form-container">
        <label for="city">City</label>
        <input class="form"type="text" id="city" name="city" value="{{old('city') ?? $data->customer->city}}">
        @error('city')
        <div class='error'>
        {{ $message }}
        </div>
        @enderror
      </div>

      <div class="form-container">
        <label for="zip">Zipcode</label>
        <input class="form"type="text" id="zip" name="zipcode" value="{{old('zipcode') ?? $data->customer->zipcode}}">
        @error('zipcode')
        <div class='error'>
        {{ $message }}
        </div>
        @enderror
      </div>

      <div class="form-container">
        <label for="state">State</label>
        <input class="form"type="text" id="state" name="state" value="{{old('state') ?? $data->customer->state}}">
        @error('state')
        <div class='error'>
        {{ $message }}
        </div>
        @enderror
      </div>

      <div class="form-container">
        <label for="state">Delivery Instruction</label>
        <input class="textarea" type="text" id="deliveryinstruction" name="deliveryinstruction" value="{{old('email') ?? $data->deliveryinstruction}}">
      </div>

      <div class="form-container">
        <label for="zip">Delivery Date</label>
        <input class="form" type="date" id="deliverydate" name="deliverydate" value= "{{old('email') ?? $data->deliverydate}}">
        @error('deliverydate')
        <div class='error'>
        {{ $message }}
        </div>
        @enderror
      </div>
     
      <div class="container1 add-item">

        <label for="itemname" >Item Name</label>
        <label for="itemname" style="padding-left:35%;">Item Quantity</label><br>
        

        @foreach ($data->item as $item)
          
            <input type="text" id="itemname" name="myItems[]"  value="{{old('itemname') ?? $item->itemname}}">
            <input type="text" id="itemquantity" name="myQuantity[]"  value="{{old('quantity') ?? $item->itemquantity}}">


            <form action="{{route('deleteItem',$item->id)}}" method="POST" style="display:contents">
     
              
            @csrf
            @method('DELETE')

                       
             <button type="submit" value='delete' name='action' class="btn btn-danger"><i class="fa fa-minus"></i></button>
            </form>
            

        @endforeach
        
        
        <button class="add_form_field btn btn-primary"><i class="fa fa-plus"></i></button>

        
      </div>
      @method('PUT')
      <div class="form-container"><button type="submit" name='action' value='update' class="btn btn-primary">Submit</button>  </div>
      
    </div>
  </form>
  <div class="form-container">
    
      
      <button onclick="document.getElementById('deleteModal').style.display='block'" class="btn btn-danger">Delete</button>
      <div id="deleteModal" class="modal">
        <span onclick="document.getElementById('deleteModal').style.display='none'" class="close" title="Close Modal">×</span>
        <form class="modal-content" action="{{route('list.destroy',[$id])}}" method="POST">

          @csrf
          @method('DELETE')
          <div class="form-container" style="text-align: center">
            <h1>Delete Order # <?php echo $data->id ?></h1>
            <p>Are you sure you want to delete your order?</p>
          
            <div class="clearfix">
              <button type="button" onclick="document.getElementById('deleteModal').style.display='none'" class="cancelbtn">Cancel</button>
              
              <button type="submit" onclick="document.getElementById('deleteModal').style.display='none'" class="deletebtn">Delete</button>
              </form>
              
              
            </div>
          </div>
        </form>
      </div>


  
  </div>
 
  @endforeach
</div>

<script>
  // Get the modal
var modal = document.getElementById('deleteModal');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "block";
  }
}

$(document).ready(function() {
  var max_fields = 40;
  var wrapper = $(".container1");
  var add_button = $(".add_form_field");

  var x = 1;
  $(add_button).click(function(e) {
    e.preventDefault();
    if (x < max_fields) {
      x++;
        $(wrapper).append('<div class="row " style="display:contents""><input type="text" name="myItems[]"placeholder="Item name" style="padding-right: 10%" > <input type="text" name="myQuantity[]"placeholder="Item quantity"> <a href="javascript:void(0);" class="delete btn btn-danger"><i class="fa fa-minus"></i></a></div>'); //add input box
    } 
  
  });

  $(wrapper).on("click", ".delete", function(e) {
    if(x>1){
      e.preventDefault();
      $(this).closest('div.row').remove();
      x--;
    }
    
  })
});
</script>


@endsection

resources/views/List/list.blade.php
@extends ('layouts.app')

@section('content')	
	<div class="container content">
		<h2 class="content-heading">Order List</h2>

		<!-- button to create a new custom order -->
    	<button type="button" class="btn btn-primary">
			<a href="{{url('list/create')}}"><i class="fa fa-plus"></i> New Order</a>
		</button>

		<!-- filter bar -->
		<div class="search-group">
			<input type="text" id="searchInput" onkeyup="filterTable()"
         		placeholder="Search" title="Type in a order" />
			<i class="fa fa-search"></i>
		</div>

		<!-- creating a table to display all orders with status 1/list -->
		<table class="order-list" id="searchTable"> 
			<tr>
				<th>Order Number</th>
				<th>Name</th>
				<th>Item</th>
				<th>Address</th>
				<th>Delivery Date</th>
				<th>Action</th>
			</tr>
			@foreach($data as $customer)

				
			<tr>
				<td>
					<!-- displaying order details when hover over order number -->
					<div class="dropdown">
						<span><u>{{$customer->id}}</u><span>
						<div class="dropdown-content">
							<div><b>Order #:</b> {{$customer->id}}</div>
							<div><b>Customer ID #:</b> {{$customer->customer->id}}</div>
							<div><b>Name: </b>	{{$customer->customer->firstname}} {{$customer->customer->lastname}} </div>
							<div><b>Email: </b>{{$customer->customer->email}}</div>
							<div><b>Address: </b>{{$customer->customer->address}}</div>
							<div><b>City: </b>{{$customer->customer->city}}</div>
							<div><b>Zipcode: </b>{{$customer->customer->zipcode}}</div>
							<div><b>State: </b>{{$customer->customer->state}}</div>
							<div><b>Delivery Date:</b> {{$customer->deliverydate}}</div>
							<div><b>Delivery instruction: </b>{{$customer->deliveryinstruction}}</div>
							<div><b>Items: </b> </div>

							<!-- displaying all items in an order -->
							@foreach($customer->item as $item)
								{{$item->itemname}} x {{$item->itemquantity}}<br>
							@endforeach
						</div>
					</div> 
				</td>

				<!-- displaying customer first and last name -->
				<td>{{$customer->customer->firstname}} {{$customer->customer->lastname}}</td>
				
				<!-- displaying all items in an order -->
				<td>
					@foreach($customer->item as $item)
								{{$item->itemname}} x {{$item->itemquantity}}<br>
					@endforeach
				</td>

				<!-- displaying order delivery zipcode -->
				<td>{{$customer->customer->city}}, {{@substr($customer->customer->zipcode, 0,5)}}</td>

				
				<td>{{date('m-d-Y', strtotime($customer->deliverydate))}}</td>
				<td>

					<!-- a button to push the order into the queue/2 -->
					<button class="btn btn-primary">
						<a href="{{url('/push/'.$customer->id)}}"><i class="fa fa-arrow-up"></i> Push</a>
					</button>

					<!-- a button to edit an order -->
					<button class="btn btn-warning">
						<a href="{{ url('list/' . $customer->id . '/edit') }}"><i class="fa fa-edit"></i> Edit</a>
						
					</button>
				</td>
			</tr>
			@endforeach <!-- end of order list foreach -->
		</table> <!-- end of table -->
			
			<!-- creating a pagination select -->
			<div class="paginate">
				<div class="paginate-select">
					<form>
						Show
						<select id="pagination">
							<option value="5"  @if($items == 5) selected @endif >5</option>
							<option value="10" @if($items == 10) selected @endif >10</option>
							<option value="25" @if($items == 25) selected @endif >25</option>
							<option value="50" @if($items == 50) selected @endif >50</option>
						</select>
						entries
					</form>
				</div>
				<div class="paginate-bar">
					<!-- displaying to buttons to go to next page or back -->
			
				{{$data->links()}}
				</div>
				

			</div>
			
			
			
	</div> 
    
    <!-- script to get what pagination select option was selected -->
    <script>
        document.getElementById('pagination').onchange = function() {

            window.location = "{{route('list')}}?page=1&items=" + this.value;
        };
    </script>

@endsection